#ifndef INCLUDE_XCSHELL_CONSTANTS_H_
#define INCLUDE_XCSHELL_CONSTANTS_H_

#define SUCCESS 0

#define ERROR_CODE_DEFAULT -1
#define ERROR_CODE_SYSTEM -1

#define REDIRECT_OUTPUT_OVERWRITE ">"
#define REDIRECT_OUTPUT_APPEND ">>"
#define REDIRECT_OUTPUT_HIDE_OVERWRITE "1>"
#define REDIRECT_OUTPUT_HIDE_APPEND "1>>"
#define REDIRECT_INPUT "<"
#define REDIRECT_PIPE "|"

#define GLOBAL_CONFIG_FILE "/etc/xcshrc"

#define USER_CONFIG_FILE "~/.xcshrc"

#endif  // INCLUDE_XCSHELL_CONSTANTS_H_
