name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        on: [ubuntu-20.04, macos-10.15]
    steps:
      - uses: actions/setup-python@v1
      - name: Install cpplint && conan
        run: |
            python -m pip install --upgrade pip
            pip install cpplint==1.4.5
            pip install conan
            pip install conan_package_tools
      - uses: actions/checkout@v2
      - name: build & test
        run: ./auto/test.sh
      - name: lint
        run: ./auto/lint.sh
